# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-01 13:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nombre')),
                ('phone', models.CharField(max_length=150, verbose_name='Telefono')),
                ('createDate', models.DateTimeField(auto_now=True, verbose_name='Fecha de creado')),
                ('lastDate', models.DateTimeField(auto_now_add=True, verbose_name='Ultima fecha modificado')),
                ('delete', models.BooleanField(default=False, verbose_name='Borrado')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driverCreator', to=settings.AUTH_USER_MODEL, verbose_name='U. Creado')),
            ],
            options={
                'verbose_name': 'Conductor',
                'verbose_name_plural': 'Conductores',
            },
        ),
        migrations.CreateModel(
            name='Truck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate', models.CharField(max_length=150, unique=True, verbose_name='Patente')),
                ('is_rent', models.BooleanField(verbose_name='Es arrendado?')),
                ('createDate', models.DateTimeField(auto_now=True, verbose_name='Fecha de creado')),
                ('lastDate', models.DateTimeField(auto_now_add=True, verbose_name='Ultima fecha modificado')),
                ('delete', models.BooleanField(default=False, verbose_name='Borrado')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='truckCreator', to=settings.AUTH_USER_MODEL, verbose_name='U. Creado')),
            ],
            options={
                'verbose_name': 'Cami\xf3n',
                'verbose_name_plural': 'Camiones',
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Nombre')),
                ('phone', models.CharField(max_length=150, verbose_name='Telefono')),
                ('rep', models.CharField(max_length=150, verbose_name='Representante')),
                ('createDate', models.DateTimeField(auto_now=True, verbose_name='Fecha de creado')),
                ('lastDate', models.DateTimeField(auto_now_add=True, verbose_name='Ultima fecha modificado')),
                ('delete', models.BooleanField(default=False, verbose_name='Borrado')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouseCreator', to=settings.AUTH_USER_MODEL, verbose_name='U. Creado')),
            ],
            options={
                'verbose_name': 'Bodega',
                'verbose_name_plural': 'Bodegas',
            },
        ),
    ]
