# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-01 13:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('intranet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Freight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createDate', models.DateTimeField(auto_now=True, verbose_name='Fecha de creado')),
                ('sendDate', models.DateTimeField(null=True, verbose_name='Fecha de envio')),
                ('receiveDate', models.DateTimeField(null=True, verbose_name='Fecha de recibido')),
                ('lastDate', models.DateTimeField(auto_now_add=True, verbose_name='Ultima fecha modificado')),
                ('is_waiting', models.BooleanField(default=True, verbose_name='Esta esperando?')),
                ('is_traveling', models.BooleanField(default=False, verbose_name='Esta viajando?')),
                ('delete', models.BooleanField(default=False, verbose_name='Borrado')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='freightCreator', to=settings.AUTH_USER_MODEL, verbose_name='U. Creado')),
                ('driver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='intranet.Driver', verbose_name='Conductor')),
                ('finish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='travelFinish', to='intranet.Warehouse', verbose_name='Bodega destino')),
                ('receiver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='freightReceiver', to=settings.AUTH_USER_MODEL, verbose_name='U. recibido')),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='freightSender', to=settings.AUTH_USER_MODEL, verbose_name='U. Envio')),
                ('start', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='travelStart', to='intranet.Warehouse', verbose_name='Bodega inicio')),
                ('truck', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='intranet.Truck', verbose_name='Camion')),
            ],
            options={
                'verbose_name': 'Manifiesto de carga',
                'verbose_name_plural': 'Manifiestos de carga',
            },
        ),
    ]
