# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-06 15:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('rut', models.CharField(max_length=150, unique=True)),
                ('address', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=150)),
                ('rep', models.CharField(max_length=150)),
                ('pay', models.CharField(max_length=150)),
                ('createDate', models.DateTimeField(auto_now=True)),
                ('lastDate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=150)),
                ('createDate', models.DateTimeField(auto_now=True)),
                ('lastDate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Freight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authorName', models.CharField(max_length=300)),
                ('createDate', models.DateTimeField(auto_now=True)),
                ('sendDate', models.DateTimeField(null=True)),
                ('lastDate', models.DateTimeField(auto_now_add=True)),
                ('is_waiting', models.BooleanField(default=True)),
                ('is_traveling', models.BooleanField(default=False)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.Driver')),
            ],
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, null=True)),
                ('sender', models.CharField(max_length=300)),
                ('authorName', models.CharField(max_length=300)),
                ('address', models.CharField(max_length=300, null=True)),
                ('createDate', models.DateTimeField(auto_now=True)),
                ('sendDate', models.DateTimeField(null=True)),
                ('lastDate', models.DateTimeField(auto_now_add=True)),
                ('is_waiting', models.BooleanField(default=True)),
                ('risk', models.CharField(max_length=100, null=True)),
                ('volume', models.CharField(max_length=100, null=True)),
                ('quantity', models.CharField(max_length=100, null=True)),
                ('weight', models.CharField(max_length=100, null=True)),
                ('chance', models.CharField(max_length=100, null=True)),
                ('rate', models.CharField(max_length=100, null=True)),
                ('pay', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Truck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate', models.CharField(max_length=150, unique=True)),
                ('is_own', models.BooleanField()),
                ('createDate', models.DateTimeField(auto_now=True)),
                ('lastDate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('phone', models.CharField(max_length=150)),
                ('representative', models.CharField(max_length=150)),
                ('createDate', models.DateTimeField(auto_now=True)),
                ('lastDate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='package',
            name='finish',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packageFinish', to='login.Warehouse'),
        ),
        migrations.AddField(
            model_name='package',
            name='freight',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='login.Freight'),
        ),
        migrations.AddField(
            model_name='package',
            name='start',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packageStart', to='login.Warehouse'),
        ),
        migrations.AddField(
            model_name='freight',
            name='finish',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='travelFinish', to='login.Warehouse'),
        ),
        migrations.AddField(
            model_name='freight',
            name='start',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='travelStart', to='login.Warehouse'),
        ),
        migrations.AddField(
            model_name='freight',
            name='truck',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.Truck'),
        ),
    ]
