# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-06 16:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='sender',
        ),
        migrations.AddField(
            model_name='package',
            name='customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='login.Customer'),
            preserve_default=False,
        ),
    ]
