# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-06 16:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20170106_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='freight',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='login.Freight'),
        ),
    ]
