# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-06 18:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_auto_20170106_1329'),
    ]

    operations = [
        migrations.RenameField(
            model_name='warehouse',
            old_name='representative',
            new_name='rep',
        ),
    ]
