# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-06 19:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_auto_20170106_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='repAddress',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='customer',
            name='repEmail',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='customer',
            name='repPhone',
            field=models.CharField(max_length=150),
        ),
    ]
