# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-06 20:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_auto_20170106_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freight',
            name='driver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='login.Driver'),
        ),
        migrations.AlterField(
            model_name='freight',
            name='truck',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='login.Truck'),
        ),
    ]
