# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-09 20:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0008_auto_20170106_1911'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='is_delivered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='package',
            name='is_traveling',
            field=models.BooleanField(default=False),
        ),
    ]
