# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-10 01:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0009_auto_20170109_1712'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='is_transmitter',
            field=models.BooleanField(default=False),
        ),
    ]
