# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-10 03:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0011_auto_20170110_0032'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='is_receiver',
            field=models.BooleanField(default=False),
        ),
    ]
