# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-10 23:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0012_package_is_receiver'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customer',
            managers=[
                ('LogicCustomer', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='driver',
            managers=[
                ('LogicDriver', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='freight',
            managers=[
                ('LogicFreight', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='package',
            managers=[
                ('LogicPackage', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='truck',
            managers=[
                ('LogicTruck', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='warehouse',
            managers=[
                ('LogicWarehouse', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='driver',
            name='delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='freight',
            name='delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='package',
            name='delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='truck',
            name='delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='delete',
            field=models.BooleanField(default=False),
        ),
    ]
