# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-12 19:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('login', '0015_auto_20170112_1624'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='sendDate',
        ),
        migrations.AddField(
            model_name='freight',
            name='receiveDate',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='freight',
            name='receiver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='freightReceiver', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='freight',
            name='sender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='freightSender', to=settings.AUTH_USER_MODEL),
        ),
    ]
