# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-12 20:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0017_auto_20170112_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='deliverer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='packageDeliverer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='package',
            name='transmitter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='packageTransmitter', to=settings.AUTH_USER_MODEL),
        ),
    ]
