# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-13 04:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0018_auto_20170112_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='createDate',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='package',
            name='lastDate',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
