# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-16 03:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0019_auto_20170113_0147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='rate',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
