# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-23 03:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0020_auto_20170116_0035'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='package',
            options={'ordering': ['-createDate']},
        ),
        migrations.AlterModelManagers(
            name='warehouse',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='freight',
            name='authorName',
        ),
        migrations.RemoveField(
            model_name='package',
            name='authorName',
        ),
    ]
