# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-26 16:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0021_auto_20170123_0058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='rep',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='repAddress',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='repEmail',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='repPhone',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='package',
            name='quantity',
            field=models.IntegerField(null=True),
        ),
    ]
