# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-31 20:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0022_auto_20170126_1329'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name': 'Cliente', 'verbose_name_plural': 'Clientes'},
        ),
        migrations.AlterModelOptions(
            name='driver',
            options={'verbose_name': 'Conductor', 'verbose_name_plural': 'Conductores'},
        ),
        migrations.AlterModelOptions(
            name='freight',
            options={'verbose_name': 'Manifiesto de carga', 'verbose_name_plural': 'Manifiestos de carga'},
        ),
        migrations.AlterModelOptions(
            name='package',
            options={'ordering': ['-createDate'], 'verbose_name': 'Guia de flete', 'verbose_name_plural': 'Guias de flete'},
        ),
        migrations.AlterModelOptions(
            name='truck',
            options={'verbose_name': 'Cami\xf3n', 'verbose_name_plural': 'Camiones'},
        ),
        migrations.AlterModelOptions(
            name='warehouse',
            options={'verbose_name': 'Bodega', 'verbose_name_plural': 'Bodegas'},
        ),
        migrations.AlterModelManagers(
            name='customer',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='driver',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='freight',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='package',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='truck',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='package',
            name='address',
        ),
        migrations.AddField(
            model_name='package',
            name='boleta',
            field=models.IntegerField(null=True, verbose_name='Boleta'),
        ),
        migrations.AddField(
            model_name='package',
            name='consignee',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='packageConsignee', to='login.Customer', verbose_name='Consignatario'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='package',
            name='is_boleta',
            field=models.BooleanField(default=False, verbose_name='Es boleta?'),
        ),
        migrations.AddField(
            model_name='package',
            name='payer',
            field=models.BooleanField(default=False, verbose_name='Paga el proveedor?'),
        ),
        migrations.AddField(
            model_name='package',
            name='provider',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='packageProvider', to='login.Customer', verbose_name='Prooveedor'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.CharField(max_length=150, verbose_name='Direccion'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='createDate',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de creado'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customerCreator', to=settings.AUTH_USER_MODEL, verbose_name='U. Creado'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='delete',
            field=models.BooleanField(default=False, verbose_name='Borrado'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='lastDate',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Ultima fecha modificado'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='pay',
            field=models.CharField(max_length=150, verbose_name='Forma de pago'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(max_length=150, verbose_name='Telefono'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='rep',
            field=models.CharField(max_length=150, null=True, verbose_name='Representante'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='repAddress',
            field=models.CharField(max_length=150, null=True, verbose_name='Direccion Representante'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='repEmail',
            field=models.CharField(max_length=150, null=True, verbose_name='Email Representante'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='repPhone',
            field=models.CharField(max_length=150, null=True, verbose_name='Telefono Representante'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='rut',
            field=models.CharField(max_length=150, unique=True, verbose_name='Rut'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='createDate',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de creado'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driverCreator', to=settings.AUTH_USER_MODEL, verbose_name='U. Creado'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='delete',
            field=models.BooleanField(default=False, verbose_name='Borrado'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='lastDate',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Ultima fecha modificado'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='phone',
            field=models.CharField(max_length=150, verbose_name='Telefono'),
        ),
        migrations.AlterField(
            model_name='freight',
            name='createDate',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de creado'),
        ),
        migrations.AlterField(
            model_name='freight',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='freightCreator', to=settings.AUTH_USER_MODEL, verbose_name='U. Creado'),
        ),
        migrations.AlterField(
            model_name='freight',
            name='delete',
            field=models.BooleanField(default=False, verbose_name='Borrado'),
        ),
        migrations.AlterField(
            model_name='freight',
            name='driver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='login.Driver', verbose_name='Conductor'),
        ),
        migrations.AlterField(
            model_name='freight',
            name='finish',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='travelFinish', to='login.Warehouse', verbose_name='Bodega destino'),
        ),
        migrations.AlterField(
            model_name='freight',
            name='is_traveling',
            field=models.BooleanField(default=False, verbose_name='Esta viajando?'),
        ),
        migrations.AlterField(
            model_name='freight',
            name='is_waiting',
            field=models.BooleanField(default=True, verbose_name='Esta esperando?'),
        ),
        migrations.AlterField(
            model_name='freight',
            name='lastDate',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Ultima fecha modificado'),
        ),
        migrations.AlterField(
            model_name='freight',
            name='receiveDate',
            field=models.DateTimeField(null=True, verbose_name='Fecha de recibido'),
        ),
        migrations.AlterField(
            model_name='freight',
            name='receiver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='freightReceiver', to=settings.AUTH_USER_MODEL, verbose_name='U. recibido'),
        ),
        migrations.AlterField(
            model_name='freight',
            name='sendDate',
            field=models.DateTimeField(null=True, verbose_name='Fecha de envio'),
        ),
        migrations.AlterField(
            model_name='freight',
            name='sender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='freightSender', to=settings.AUTH_USER_MODEL, verbose_name='U. Envio'),
        ),
        migrations.AlterField(
            model_name='freight',
            name='start',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='travelStart', to='login.Warehouse', verbose_name='Bodega inicio'),
        ),
        migrations.AlterField(
            model_name='freight',
            name='truck',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='login.Truck', verbose_name='Camion'),
        ),
        migrations.AlterField(
            model_name='package',
            name='chance',
            field=models.CharField(max_length=100, null=True, verbose_name='Oportunidad'),
        ),
        migrations.AlterField(
            model_name='package',
            name='createDate',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creacion'),
        ),
        migrations.AlterField(
            model_name='package',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packageCreator', to=settings.AUTH_USER_MODEL, verbose_name='U. Creado'),
        ),
        migrations.AlterField(
            model_name='package',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packageCustomer', to='login.Customer', verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='package',
            name='delete',
            field=models.BooleanField(default=False, verbose_name='Borrado'),
        ),
        migrations.AlterField(
            model_name='package',
            name='deliverDate',
            field=models.DateTimeField(null=True, verbose_name='Entrega'),
        ),
        migrations.AlterField(
            model_name='package',
            name='deliverer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='packageDeliverer', to=settings.AUTH_USER_MODEL, verbose_name='U. Entregado'),
        ),
        migrations.AlterField(
            model_name='package',
            name='finish',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packageFinish', to='login.Warehouse', verbose_name='Destino'),
        ),
        migrations.AlterField(
            model_name='package',
            name='finishAddress',
            field=models.CharField(max_length=300, null=True, verbose_name='Direcci\xf3n destino'),
        ),
        migrations.AlterField(
            model_name='package',
            name='freight',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='login.Freight', verbose_name='Manifiesto de carga'),
        ),
        migrations.AlterField(
            model_name='package',
            name='is_delivered',
            field=models.BooleanField(default=False, verbose_name='Fue entregado?'),
        ),
        migrations.AlterField(
            model_name='package',
            name='is_receiver',
            field=models.BooleanField(default=False, verbose_name='Ir a entregar?'),
        ),
        migrations.AlterField(
            model_name='package',
            name='is_transmitter',
            field=models.BooleanField(default=False, verbose_name='Ir a buscar?'),
        ),
        migrations.AlterField(
            model_name='package',
            name='is_traveling',
            field=models.BooleanField(default=False, verbose_name='Esta viajando?'),
        ),
        migrations.AlterField(
            model_name='package',
            name='is_waiting',
            field=models.BooleanField(default=True, verbose_name='Esta esperando?'),
        ),
        migrations.AlterField(
            model_name='package',
            name='lastDate',
            field=models.DateTimeField(auto_now=True, verbose_name='Ultima modificaci\xf3n'),
        ),
        migrations.AlterField(
            model_name='package',
            name='name',
            field=models.CharField(max_length=300, null=True, verbose_name='Descripci\xf3n'),
        ),
        migrations.AlterField(
            model_name='package',
            name='pay',
            field=models.CharField(max_length=100, null=True, verbose_name='Forma de pago'),
        ),
        migrations.AlterField(
            model_name='package',
            name='quantity',
            field=models.IntegerField(null=True, verbose_name='Cantidad'),
        ),
        migrations.AlterField(
            model_name='package',
            name='rate',
            field=models.IntegerField(verbose_name='Tarifado'),
        ),
        migrations.AlterField(
            model_name='package',
            name='risk',
            field=models.CharField(max_length=100, null=True, verbose_name='Riesgo'),
        ),
        migrations.AlterField(
            model_name='package',
            name='start',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packageStart', to='login.Warehouse', verbose_name='Origen'),
        ),
        migrations.AlterField(
            model_name='package',
            name='startAddress',
            field=models.CharField(max_length=300, null=True, verbose_name='Direcci\xf3n origen'),
        ),
        migrations.AlterField(
            model_name='package',
            name='transmitDate',
            field=models.DateTimeField(null=True, verbose_name='Ido a buscar'),
        ),
        migrations.AlterField(
            model_name='package',
            name='transmitter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='packageTransmitter', to=settings.AUTH_USER_MODEL, verbose_name='U. Ir a buscar'),
        ),
        migrations.AlterField(
            model_name='package',
            name='volume',
            field=models.CharField(max_length=100, null=True, verbose_name='Volumen'),
        ),
        migrations.AlterField(
            model_name='package',
            name='weight',
            field=models.CharField(max_length=100, null=True, verbose_name='Peso'),
        ),
        migrations.AlterField(
            model_name='truck',
            name='createDate',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de creado'),
        ),
        migrations.AlterField(
            model_name='truck',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='truckCreator', to=settings.AUTH_USER_MODEL, verbose_name='U. Creado'),
        ),
        migrations.AlterField(
            model_name='truck',
            name='delete',
            field=models.BooleanField(default=False, verbose_name='Borrado'),
        ),
        migrations.AlterField(
            model_name='truck',
            name='is_rent',
            field=models.BooleanField(verbose_name='Es arrendado?'),
        ),
        migrations.AlterField(
            model_name='truck',
            name='lastDate',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Ultima fecha modificado'),
        ),
        migrations.AlterField(
            model_name='truck',
            name='plate',
            field=models.CharField(max_length=150, unique=True, verbose_name='Patente'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='createDate',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de creado'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouseCreator', to=settings.AUTH_USER_MODEL, verbose_name='U. Creado'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='delete',
            field=models.BooleanField(default=False, verbose_name='Borrado'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='lastDate',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Ultima fecha modificado'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='name',
            field=models.CharField(max_length=150, unique=True, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='phone',
            field=models.CharField(max_length=150, verbose_name='Telefono'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='rep',
            field=models.CharField(max_length=150, verbose_name='Representante'),
        ),
    ]
