# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-31 22:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0023_auto_20170131_1721'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='pay',
        ),
        migrations.AddField(
            model_name='package',
            name='credit',
            field=models.BooleanField(default=False, verbose_name='Forma de pago'),
        ),
    ]
