# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-01 13:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0024_auto_20170131_1943'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='freight',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='freight',
            name='driver',
        ),
        migrations.RemoveField(
            model_name='freight',
            name='finish',
        ),
        migrations.RemoveField(
            model_name='freight',
            name='receiver',
        ),
        migrations.RemoveField(
            model_name='freight',
            name='sender',
        ),
        migrations.RemoveField(
            model_name='freight',
            name='start',
        ),
        migrations.RemoveField(
            model_name='freight',
            name='truck',
        ),
        migrations.RemoveField(
            model_name='package',
            name='consignee',
        ),
        migrations.RemoveField(
            model_name='package',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='package',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='package',
            name='deliverer',
        ),
        migrations.RemoveField(
            model_name='package',
            name='finish',
        ),
        migrations.RemoveField(
            model_name='package',
            name='freight',
        ),
        migrations.RemoveField(
            model_name='package',
            name='provider',
        ),
        migrations.RemoveField(
            model_name='package',
            name='start',
        ),
        migrations.RemoveField(
            model_name='package',
            name='transmitter',
        ),
        migrations.RemoveField(
            model_name='truck',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='warehouse',
            name='creator',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='Driver',
        ),
        migrations.DeleteModel(
            name='Freight',
        ),
        migrations.DeleteModel(
            name='Package',
        ),
        migrations.DeleteModel(
            name='Truck',
        ),
        migrations.DeleteModel(
            name='Warehouse',
        ),
    ]
