# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-01 13:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('freights', '0001_initial'),
        ('intranet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, null=True, verbose_name='Descripci\xf3n')),
                ('lastDate', models.DateTimeField(auto_now=True, verbose_name='Ultima modificaci\xf3n')),
                ('createDate', models.DateTimeField(auto_now_add=True, verbose_name='Creacion')),
                ('deliverDate', models.DateTimeField(null=True, verbose_name='Entrega')),
                ('transmitDate', models.DateTimeField(null=True, verbose_name='Ido a buscar')),
                ('startAddress', models.CharField(max_length=300, null=True, verbose_name='Direcci\xf3n origen')),
                ('finishAddress', models.CharField(max_length=300, null=True, verbose_name='Direcci\xf3n destino')),
                ('is_waiting', models.BooleanField(default=True, verbose_name='Esta esperando?')),
                ('is_traveling', models.BooleanField(default=False, verbose_name='Esta viajando?')),
                ('is_delivered', models.BooleanField(default=False, verbose_name='Fue entregado?')),
                ('is_transmitter', models.BooleanField(default=False, verbose_name='Ir a buscar?')),
                ('is_receiver', models.BooleanField(default=False, verbose_name='Ir a entregar?')),
                ('is_boleta', models.BooleanField(default=False, verbose_name='Es boleta?')),
                ('boleta', models.IntegerField(null=True, verbose_name='Boleta')),
                ('risk', models.CharField(max_length=100, null=True, verbose_name='Riesgo')),
                ('volume', models.CharField(max_length=100, null=True, verbose_name='Volumen')),
                ('quantity', models.IntegerField(null=True, verbose_name='Cantidad')),
                ('weight', models.CharField(max_length=100, null=True, verbose_name='Peso')),
                ('chance', models.CharField(max_length=100, null=True, verbose_name='Oportunidad')),
                ('rate', models.IntegerField(verbose_name='Tarifado')),
                ('credit', models.BooleanField(default=False, verbose_name='Forma de pago')),
                ('payer', models.BooleanField(default=False, verbose_name='Paga el proveedor?')),
                ('delete', models.BooleanField(default=False, verbose_name='Borrado')),
                ('consignee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packageConsignee', to='customers.Customer', verbose_name='Consignatario')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packageCreator', to=settings.AUTH_USER_MODEL, verbose_name='U. Creado')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packageCustomer', to='customers.Customer', verbose_name='Cliente')),
                ('deliverer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='packageDeliverer', to=settings.AUTH_USER_MODEL, verbose_name='U. Entregado')),
                ('finish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packageFinish', to='intranet.Warehouse', verbose_name='Destino')),
                ('freight', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='freights.Freight', verbose_name='Manifiesto de carga')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packageProvider', to='customers.Customer', verbose_name='Prooveedor')),
                ('start', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packageStart', to='intranet.Warehouse', verbose_name='Origen')),
                ('transmitter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='packageTransmitter', to=settings.AUTH_USER_MODEL, verbose_name='U. Ir a buscar')),
            ],
            options={
                'ordering': ['-createDate'],
                'verbose_name': 'Guia de flete',
                'verbose_name_plural': 'Guias de flete',
            },
        ),
    ]
