# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-03 02:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customers', '0001_initial'),
        ('intranet', '0001_initial'),
        ('packages', '0004_auto_20170202_2103'),
    ]

    operations = [
        migrations.CreateModel(
            name='PickUp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastDate', models.DateTimeField(auto_now=True, verbose_name='Ultima modificaci\xf3n')),
                ('createDate', models.DateTimeField(auto_now_add=True, verbose_name='Creacion')),
                ('pickUpDate', models.DateTimeField(null=True, verbose_name='Entrega')),
                ('address', models.CharField(max_length=300, null=True, verbose_name='Direcci\xf3n destino')),
                ('is_waiting', models.BooleanField(default=True, verbose_name='Esta esperando?')),
                ('quantity', models.IntegerField(null=True, verbose_name='Cantidad')),
                ('weight', models.CharField(max_length=100, null=True, verbose_name='Peso')),
                ('delete', models.BooleanField(default=False, verbose_name='Borrado')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pickUpCreator', to=settings.AUTH_USER_MODEL, verbose_name='U. Creado')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pickUpCustomer', to='customers.Customer', verbose_name='Cliente')),
                ('deliverer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pickUpDeliverer', to=settings.AUTH_USER_MODEL, verbose_name='U. Recibido')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pickUpWarehouse', to='intranet.Warehouse', verbose_name='Bodega')),
            ],
            options={
                'ordering': ['-createDate'],
                'verbose_name': 'Recogida de carga',
                'verbose_name_plural': 'Recogidas de carga',
            },
        ),
    ]
