# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-04 18:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0001_initial'),
        ('packages', '0006_auto_20170203_0031'),
    ]

    operations = [
        migrations.AddField(
            model_name='pickup',
            name='driver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='intranet.Driver', verbose_name='Conductor'),
        ),
        migrations.AddField(
            model_name='pickup',
            name='truck',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='intranet.Truck', verbose_name='Camion'),
        ),
    ]
