# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-10 14:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0007_auto_20170204_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='packaging',
            field=models.CharField(max_length=100, null=True, verbose_name='Embalage'),
        ),
    ]
