# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-10 15:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0008_package_packaging'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='weight',
        ),
        migrations.AddField(
            model_name='package',
            name='is_weight',
            field=models.BooleanField(default=False, verbose_name='Forma de Tarifado'),
        ),
    ]
