# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-13 04:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0010_package_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='packageCustomer', to='customers.Customer', verbose_name='Cliente'),
        ),
    ]
