# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-15 13:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0011_auto_20170313_0120'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='unknown_pay_method',
            field=models.BooleanField(default=False, verbose_name='Se desconoce forma de pago?'),
        ),
    ]
