# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-22 17:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0012_package_unknown_pay_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='old_id',
            field=models.IntegerField(null=True, verbose_name='Guia modificada'),
        ),
    ]
