# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-22 20:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0013_package_old_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='old',
            field=models.BooleanField(default=False, verbose_name='Guia antigua'),
        ),
        migrations.AlterField(
            model_name='package',
            name='old_id',
            field=models.IntegerField(null=True, verbose_name='Guia anterior'),
        ),
    ]
