# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-23 00:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0015_auto_20170322_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='boleta',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Boleta'),
        ),
        migrations.AlterField(
            model_name='package',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='packageCustomer', to='customers.Customer', verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='package',
            name='deliverDate',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Entrega'),
        ),
        migrations.AlterField(
            model_name='package',
            name='deliverer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='packageDeliverer', to=settings.AUTH_USER_MODEL, verbose_name='U. Entregado'),
        ),
        migrations.AlterField(
            model_name='package',
            name='finishAddress',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Direcci\xf3n destino'),
        ),
        migrations.AlterField(
            model_name='package',
            name='name',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Descripci\xf3n'),
        ),
        migrations.AlterField(
            model_name='package',
            name='old_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Guia anterior'),
        ),
        migrations.AlterField(
            model_name='package',
            name='volume',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Volumen'),
        ),
        migrations.AlterField(
            model_name='package',
            name='weight',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Peso'),
        ),
    ]
