# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-01 13:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nombre')),
                ('rut', models.CharField(max_length=150, unique=True, verbose_name='Rut')),
                ('address', models.CharField(max_length=150, verbose_name='Direccion')),
                ('phone', models.CharField(max_length=150, verbose_name='Telefono')),
                ('rep', models.CharField(max_length=150, null=True, verbose_name='Representante')),
                ('repAddress', models.CharField(max_length=150, null=True, verbose_name='Direccion Representante')),
                ('repEmail', models.CharField(max_length=150, null=True, verbose_name='Email Representante')),
                ('repPhone', models.CharField(max_length=150, null=True, verbose_name='Telefono Representante')),
                ('pay', models.CharField(max_length=150, verbose_name='Forma de pago')),
                ('createDate', models.DateTimeField(auto_now=True, verbose_name='Fecha de creado')),
                ('lastDate', models.DateTimeField(auto_now_add=True, verbose_name='Ultima fecha modificado')),
                ('delete', models.BooleanField(default=False, verbose_name='Borrado')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customerCreator', to=settings.AUTH_USER_MODEL, verbose_name='U. Creado')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
    ]
